name: Test TCD

on:
  workflow_dispatch:

jobs:
  run-tcd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install .

      - name: Run TCD
        env:
          TCD_CLIENT_ID: ${{ secrets.TCD_CLIENT_ID }}
          TCD_CLIENT_SECRET: ${{ secrets.TCD_CLIENT_SECRET }}
        run: |
          tcd --video 789654123,987456321
